### ISSUE TITLE
Remove statistic when viewing single language

### ISSUE THREAD

**Issue by Remo** [concrete5/addon_community_translation#11]
I'm on `/translate/details/pkg_/dev-5.7/de_DE` to translate that language. I find it a bit confusing to see all languages on that screen. Not saying it's a big deal, just wondering what others think.

I'd probably have opened `/translate/online/41/de_DE` directly and added those buttons to upload a PO files in a dropdown on that screen. Most people should be using the translation screen and don't need that step in between. I know that the current implementation is closer to transifex which has some benefits too. Again, just speaking out loud and not complaing or anything. What's you've already built is very impressive!

![image](https://cloud.githubusercontent.com/assets/129864/13699379/4ddd6b52-e77a-11e5-89f4-6278c9010d3d.png)

**Comment by mlocati** [comment]
Well, that page exists because the system allows downloading translations even for people that are not translators: think for instance about those that just have an add-on and want to update their translation files

**Comment by Remo** [comment]
Yes and in transifex that makes sense, but I don't think this process will matter for us, but let's see what others think about that..

**Comment by mlocati** [comment]
The new online translation tool offers a way to download/upload translation files, as well as changing the version of the package being currently translated.

The upcoming block that allow users to pick the package/version they want to translate will point directly to the online translation tool.
