### ISSUE TITLE
Test wanted

### ISSUE THREAD

**Issue by mlocati** [concrete5/addon_community_translation#15]
Community Translation requires some deep testing.

Sample install instructions:

- install this package (requires the very latest version in the `develop` branch of concrete5)
- check the Community Translation options in the dashboard pages
- add an instance of every block in new pages; the blocks are:
  - `translation_team_request`: to ask the creation of translation teams
  - `translation_teams`: to view the language teams, as well as managing translation group members and join requests
  - `search_packages`: to search for packages, as well as seeing the package details, download the translations and access the online translation tool.
  - `fill_translations`: to upload a package, let Community Translation extract the translatable strings, fill-in the known translations, and download those translations.
- check that the blocks work as expected
- check that the CLI commands work as expected (they have a `ct:` prefix)

Please remark that the `admin` user has fully administration rights for Community Translation too: so, for better testing, we should test everything with other users too.

**Comment by mlocati** [comment]
PS: if you need some data, you can run these SQL queries that reset the Community Translations tables and add the current GitHub/Transifex strings: 

[CommunityTranslation.zip](https://github.com/concrete5/addon_community_translation/files/1114342/CommunityTranslation.zip)

**Comment by Remo** [comment]
Still have it on my list, but things are a bit hectic right now, probably not going to be able to have a look during the next few days..

**Comment by mlocati** [comment]
@Remo Thanks! @katzueno should be coming on board too :wink:

**Comment by danielgasser** [comment]
@mlocati  There's an error in the sql file you posted:
In a insert statement its "communitytranslationgitrepositories" instead of "CommunityTranslationGitRepositories". Fixed it

[CommunityTranslation_fixed_camelcase_table_names.sql.zip](https://github.com/concrete5/addon_community_translation/files/816673/CommunityTranslation_fixed_camelcase_table_names.sql.zip)

**Comment by mlocati** [comment]
> @mlocati There's an error in the sql file you posted:

I updated the ZIP archive [above](#issuecomment-283337923) too

**Comment by mlocati** [comment]
Guide for testers

1. Install concrete5:
1.1 it must be the very latest concrete5 version from the `develop` branch in [GitHub](https://github.com/concrete5/concrete5)
1.2 install with sample content, but after remove all the default website pages  

2. Install CommunityTranslation
2.1 download (or clone) the `master` branch from [GitHub](https://github.com/concrete5/addon_community_translation)
2.2 in order to have some data to work on, import the SQL file I [linked here](https://github.com/concrete5/addon_community_translation/issues/15#issuecomment-283337923)  

3. Setup some site pages  
  [sample approach](https://youtu.be/UX-zkrqU46w)  

4. Setup a couple of users  
  [sample approach](https://youtu.be/x9_eSGboQlo)  

5. Test teams management, translation submissions, translation approvals  
  [sample steps](https://youtu.be/4674gv6jQQc)

**Comment by mlocati** [comment]
PS: In order to make notifications work properly, we need also to give the `Translation teams list and details` block instance the name `CommunityTranslation Team List` (see https://youtu.be/y-wNhPDhiaM )

**Comment by Remo** [comment]
There's still an oauth problem, when I try to log in through concrete5.org I get this page:
![image](https://cloud.githubusercontent.com/assets/129864/24015973/9117a9a8-0a8a-11e7-8591-8db8f4c6c9e6.png)

**Comment by mlocati** [comment]
@Remo Quite strange: it's currently working flawlessly for me (and others)

**Comment by Remo** [comment]
third attempt works, this oauth feels a bit buggy..

**Comment by Remo** [comment]
Got a problem with this: https://translate.concrete5.org/translate-your-packages
Whenever I upload a file I get `Invalid form token. Please reload this form and submit again.` on the new page. If it depends on the file I'm upload, drop me a message.

**Comment by mlocati** [comment]
Others have had that problem too in case of big (> 1MB?) packages. Is your package that big?

**Comment by Remo** [comment]
I'm just uploading the POT file, 59kb. Actually you've got access to it, it's the repo you've been working on with me

**Comment by mlocati** [comment]
I finally got that error (only if I'm logged in).
This is really strange: the token is generated [here](https://github.com/concrete5/addon_community_translation/blob/0.2.7/blocks/fill_translations/view.php#L23) and it's checked [here](https://github.com/concrete5/addon_community_translation/blob/0.2.7/blocks/fill_translations/controller.php#L339) (tested with debugging)... I've never had this issue...

**Comment by Remo** [comment]
Yes, same here, if I log out it works. Strange, no idea right now

**Comment by Mnkras** [comment]
I setup everything locally and I can't repro, but I can repro on the live site...

**Comment by mlocati** [comment]
> I finally got that error (only if I'm logged in).

And on another PC I have this error only if I'm NOT logged in :wink:

**Comment by mlocati** [comment]
Let's see if https://github.com/concrete5/addon_community_translation/commit/e05d7fdfb03864a5b4c67a5478bc544a3f6a763d fixes the `Invalid form token` problem...

**Comment by mlocati** [comment]
Yes! The problem should be fixed
