### ISSUE TITLE
Adding Git Repo: constraint violation

### ISSUE THREAD

**Issue by danielgasser** [concrete5/addon_community_translation#18]
When adding a git repo (/dashboard/community_translation/git_repositories/details/new), with Parse tags set to "all" the following DB Exception occurs:

> An exception occurred while executing 'INSERT INTO CommunityTranslationGitRepositories (name, packageHandle, url, devBranches, directoryToParse, directoryForPlaces, detectedVersions, tagToVersionRegexp, tagFilters) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["concrete5-5.7-Test-Package", "test_package", "https:\/\/github.com\/danielgasser\/concrete5-5.7-Test-Package", "a:0:{}", "", "", "a:0:{}", "\/^(?:v(?:er(?:s(?:ion)?)?)?[.\\s]*)?(\\d+(?:\\.\\d+)*)$\/", null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tagFilters' cannot be null

(Add Search Packages:
Preload package always gives the error: 

No package with handle "test_package" 

even though the package is installed)

**Comment by mlocati** [comment]
I'll fix the integrity violation exception.

About the problem that "Search Package" doesn't find the "test_package" package: it means that CT don't have translations for that package. CT packages are not the ones you have installed in concrete5, they are "Translated Packages". If you import the data included in #15 and inspect the database (HeidiSQL is great on Windows), you'll be able to see that I mean in the tables that start with `CommunityTranslation`

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/addon_community_translation/commit/ec98106bfe8d40bb50ed1c0d66991edd16d34b56
