### ISSUE TITLE
Translate online: PHP file upload error

### ISSUE THREAD

**Issue by danielgasser** [concrete5/addon_community_translation#19]
Steps to reproduce (as Superuser):

0. In the Search Packages Block, click on "Translate" (any language)
1. Download translations as PHP Array
2. Edit the file
3. Upload again
Error:
> PhpArray::fromString() cannot be called. Use PhpArray::fromFile()

Exception thrown at:
/concrete/vendor/gettext/gettext/src/Extractors/PhpArray.php Line: 39

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/addon_community_translation/commit/7860b3a56acc03e23e724eed3b82295924d8a9bd
