### ISSUE TITLE
 API Access: 404 on group search url

### ISSUE THREAD

**Issue by danielgasser** [concrete5/addon_community_translation#20]
On the Community Translation Options page:

API Access:

- Retrieve statistical data
- Download translations
- Import translations from packages
- Update package translations 

gives a 404 (/index.php/ccm/dialogs/group/search). Shouldn't that url rather be: /index.php/dashboard/users/groups?

**Comment by mlocati** [comment]
The whole stuff related to API is going to be revisited, it's not yet ready

**Comment by mlocati** [comment]
Addressed by #21
