### ISSUE TITLE
Filter for unapproved/approved buggy

### ISSUE THREAD

**Issue by Remo** [concrete5/addon_community_translation#27]
I'm not sure if it's a filter or a display problem, but when we only want to see unapproved translations, the checkbox approved is still ticked.
![2017-04-04_10-01-18](https://cloud.githubusercontent.com/assets/129864/24647752/7606a5b0-1921-11e7-85ec-d8f8ed1b7f66.gif)

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/addon_community_translation/commit/a6973bd7aef918a189d9b3c19b0b281f9c8e37c0
