### ISSUE TITLE
Approval process not intuitive

### ISSUE THREAD

**Issue by Remo** [concrete5/addon_community_translation#28]
Feedback from Torsten I agree with. The approval process is a bit strange.

1. Click on "handshake" icon, we are here https://translate.concrete5.org/translate/online/unreviewed/de_DE
2. Select a string: 
![image](https://cloud.githubusercontent.com/assets/129864/24647337/ca5eb9f6-191f-11e7-8285-b773c02958b1.png)
3. Now what shall I do? If I click on "Approve", the word suggests I should, it pastes the translation suggested by the system, which is wrong by the way.

Here's another example, still in the same screen:

1. Selected "and": 
![image](https://cloud.githubusercontent.com/assets/129864/24647399/06e95ed0-1920-11e7-817f-b941c65ee75d.png)
2. Here we don't have any approve buttons, but I assume that's just because there are no suggestions, approving works through "Click on Approved" and "Save & Continue"

---

I think the words Approve & Deny are a bit misleading here.
Wouldn't `Use This` be better? The deny button I'd just remove.

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/concrete5/pull/5285 and https://github.com/concrete5/addon_community_translation/commit/4afa4a1556c5a56c25ee3e4bc0c1c79edd0c2165

**Comment by mlocati** [comment]
Deployed
