### ISSUE TITLE
Feature request: Search packages by author

### ISSUE THREAD

**Issue by a3020** [concrete5/addon_community_translation#31]
It'd be handy if you'd search packages by author. https://translate.concrete5.org/translate/search

![afbeelding](https://user-images.githubusercontent.com/1431100/39204095-16c12066-47f7-11e8-88a9-78867af924cf.png)

**Comment by mlocati** [comment]
We don't have this information...

**Comment by a3020** [comment]
OK, nevermind then ;)

**Comment by mlocati** [comment]
The data we receive from the PRB is *only* this: https://github.com/concrete5/addon_community_translation/blob/master/src/Entity/RemotePackage.php
