### ISSUE TITLE
XSS protection

### ISSUE THREAD

**Issue by mlocati** [concrete5/addon_community_translation#33]
From https://github.com/concrete5/concrete5/pull/7592#discussion_r260351029

> @mlocati I'm not sure if that's a good solution that character list is not XSS proof. Also, are we never going to use translations with e.g. '<', '=', or '"' in it? For example, we have a few strings with `<a href="some-link"` in it, right?
>
> @aembler Is there a (performance?) reason why you don't want to use `h` for all plain text occurrences? Escaping is the safest solution, imo.
> 
> @mlocati I found this on the Drupal site:
> 
> > Exported versions of approved translations are regularly saved, so **once your suggestions are approved**, they will be available in the exported translation files shortly.
> 
> Some more searching and I stumbled on this thread: https://www.drupal.org/project/drupal/issues/2512466 It seems they had this problem also, but then 4 yrs ago ;) I think the bottom line is that it's hard to prevent XSS.
> 
> At the moment, unapproved strings are used in production if there's no approved alternative available. I think that can be improved. Some (brainstorm!) ideas:
> 
>* **Only pull approved strings.** (this is what Drupal does, and I think it makes sense)
>* Wait x-hours / x-days before an unapproved string can be pulled from the translation system.
>* Having a strong policy of who can join a team / submit translations. (karma minimum?)

**Comment by mlocati** [comment]
> are we never going to use translations with e.g. '<', '=', or '"' in it?

If the source (English) string contain `<`, the translation can contain it (the same for the other chars). If the source string doesn't contain `<`, the translation can't contain it (see https://github.com/concrete5/addon_community_translation/commit/26e382024019aed4948ed9a2fb0ae1c87c663f0f#diff-dad5c49854c5a6edc130e4c8f57f50b4R457)

> Only pull approved strings

The problem in pulling only *approved* strings is that we have many translation groups that don't have coordinators.

> Having a strong policy of who can join a team / submit translations. (karma minimum?)

That's what I check when I'm asked to promote someone to be a coordinator (or when I suggest someone to become a coordinator).

**Comment by a3020** [comment]
> If the source (English) string contain `<`, the translation can contain it

OK. So if original is `<a href="f">foo</a>` I can translate it with `<a href="f">foo</a><script>alert('xss')</script>`? (I'm saying because I see a `strpos` check). Also, what about other encodings? (imo this is never going to be perfectly safe, but ok)

> The problem in pulling only _approved_ strings is that we have many translation groups that don't have coordinators.

I think missing translations are a great reason for people to join a translation team or to become a coordinator. In any case I'd prefer _few_ translations (but safe) over _many_ translations (but possibly unsafe). What's your opinion on this?

> That's what I check when I'm asked to promote someone to be a coordinator (or when I suggest 
someone to become a coordinator).

True, but current coordinators can also make other team members a coordinator. Not everybody may be as careful as you are. Some may just be happy that finally someone wants to join their team / take over...

**Comment by mlocati** [comment]
> OK. So if original is `<a href="f">foo</a>` I can translate it with `<a href="f">foo</a><script>alert('xss')</script>`

No: at https://github.com/concrete5/addon_community_translation/blob/0.6.10/src/Translation/Importer.php#L464-L478 we check that users can only add to the translations the same tag present in the English strings (if the source string contains `<a`, the translation can contains only `<a` and not other tags, like `<script`).

> current coordinators can also make other team members a coordinator. Not everybody may be as careful as you are. Some may just be happy that finally someone wants to join their team / take over...

I receive notifications about role changes, and so far nothing strange happened :wink:

**Comment by a3020** [comment]
![image](https://user-images.githubusercontent.com/1431100/53435558-5eb3ea80-39f9-11e9-9167-e741a8858df5.png)

Saved -> XSS.

**Comment by mlocati** [comment]
Any hint about how to solve this?

**Comment by a3020** [comment]
I wouldn't try to make a function that tries to prevent XSS this way. It's just never going to work 100%. 

The idea that people can submit translations that are then pulled to production websites and displayed without being approved and without being escaped, is kinda scary to me.

To me, pulling the approved strings only would be a logical step. I'm interested in how others think about it though!

**Comment by mlocati** [comment]
Another solution would bet avoid html in the source strings

**Comment by aembler** [comment]
I don't want to make your work any harder than it has to be, @mlocati – do you think it just makes sense for us to eliminate HTML in all strings by policy? 

I could imagine rewriting the above string as

    <?=t('Please note that storing form submissions can be disabled in in 8.4.4+.')?>
    <a href="<?=$url?>"><?=tc('StoringFormSubmissionURL', 'Click here to learn more.')?></a>

Or something like that.

**Comment by a3020** [comment]
Just eliminating HTML from all strings wouldn't solve the **whole** problem either. E.g. take a string like [this](https://github.com/concrete5/concrete5/blob/95e79fe32c851da4d80f1a3b3796fe8c6bfe9670/concrete/elements/gathering/templates/tile/image_description_center/view.php#L9):
```html
<img src="<?=$image->getSrc()?>" alt="<?php echo t('Preview Image') ?>" />
```

If one would translate that to `" onload="alert(1)`, you'd have XSS as well.

**Comment by mlocati** [comment]
If the English string doesn't contain `"`, the translated string can't contain it (see the new method I added to CT)

**Comment by a3020** [comment]
Fair enough. How about [this one](https://github.com/concrete5/concrete5/blob/develop/concrete/single_pages/dashboard/reports/forms/legacy.php#L25)?

```
deleteFormAnswers = '<?php echo t('Are you sure you want to delete this form submissions?') ?>';
```

E.g. `'; window.location='https://www.concrete5.org'; //`

**Comment by mlocati** [comment]
That's why I always use json_encode to send strings to javascript
