### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by mlocati** [concrete5/addon_community_translation#36]
@okhayat [reported on Slack](https://concrete5.slack.com/archives/CDJ4G93C3/p1557378897008300):

> It would be nice if the translation text area is switched to RTL for RTL langs like Arabic, Urdu and etc

I'm absolutely ignorant about RTL languages, so I'd need some support.

@okhayat could you check if doing the following fixes this issue?

1. While you are in the translation window, open your browser developer tools and go to the Console tab
2. Enter this command and hit the `Enter` key:

    ```JavaScript
    $('#comtra_translator .ccm-translator-col-translations textarea').attr('dir', 'rtl')
    ```

Screenshot for Firefox:

![image](https://user-images.githubusercontent.com/928116/57512819-0a888900-730d-11e9-8783-693470ab8a71.png)

**Comment by okhayat** [comment]
Yes. This is exactly what is needed. It will switch the writing direction to RTL and align the text right.
Appreciate your support.

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/concrete5/pull/7807 + https://github.com/concrete5/addon_community_translation/commit/89dd2a4272df4ddb7d9c1eef87af1f08a4c2a107 + https://github.com/concrete5/translate.concrete5.org/commit/f303dffaffe91f8890974ccc2933bf32fd06f144
