### ISSUE TITLE
btoa fails in chrome with mutlibyte characters

### ISSUE THREAD

**Issue by KorvinSzanto** [concrete5/addon_community_translation#52]
```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at https://translate.stage.concretecms.org/index.php/translate/online/55/th_TH:1091:74
    at Array.map (<anonymous>)
```

triggered by [this line](https://github.com/concrete5/addon_community_translation/blob/f847cd6aa5ca11a03091474e2d15fa4c2e2bf1b8/views/frontend/online_translation.php) when saving the "calendar" translation [found here](https://translate.stage.concretecms.org/index.php/translate/online/55/th_TH#tid:7615,xtab:glossary). Firefox doesn't seem to care but chrome doesn't like it.

**Comment by KorvinSzanto** [comment]
To avoid this issue [MDN recommend converting to binary before running btoa](https://developer.mozilla.org/en-US/docs/Web/API/btoa):
```js
// convert a Unicode string to a string in which
// each 16-bit unit occupies only one byte
function toBinary(string) {
  const codeUnits = new Uint16Array(string.length);
  for (let i = 0; i < codeUnits.length; i++) {
    codeUnits[i] = string.charCodeAt(i);
  }
  const charCodes = new Uint8Array(codeUnits.buffer);
  let result = '';
  for (let i = 0; i < charCodes.byteLength; i++) {
    result += String.fromCharCode(charCodes[i]);
  }
  return result;
}

// a string that contains characters occupying > 1 byte
const myString = "☸☹☺☻☼☾☿";

const converted = toBinary(myString);
const encoded = btoa(converted);
console.log(encoded);
```

**Comment by mlocati** [comment]
I was thinking about using encodeURIComponent on the client side, passing its resullt to btoa

**Comment by KorvinSzanto** [comment]
> I was thinking about using encodeURIComponent on the client side, passing its resullt to btoa

It does look like wrapping with encodeURIComponent works https://jsbin.com/ducuhaguha/1/edit?html,js,output
