### ISSUE TITLE
Do we need to check the ccm_token when downloading MO and PO files?

### ISSUE THREAD

**Issue by wordish** [concrete5/addon_community_translation#69]
All links to MO & PO files include a `ccm_token` value in the query string. When search engines eventually follow these links, they will return 500 because they've expired. Do we really need to have this check if the files are publicly available?

<img width="1304" alt="Screenshot 2023-03-20 at 14 39 49" src="https://user-images.githubusercontent.com/42463480/226471826-1c43e644-31b1-45d8-b65a-80ef40cf1b19.png">

**Comment by mlocati** [comment]
I'd simply add a response header to tell search engines to not index those links...
