### ISSUE TITLE
password prompt not working

### ISSUE THREAD

**Issue by Remo** [concrete5/addon_community_translation#7]
I guess it really doesn't matter as I expect that hardly anyone will use that package on a windows computer, but just in case. I'm getting an error:

```
C:\work\concrete5.7.5.6>concrete\bin\concrete5.bat translate:initialize transifex-translations
Please enter the Transifex username: remol
Please enter the Transifex password for remol (will be hidden): 'C:\work\concrete5.7.5.6\concrete\vendor\symfony\console\Helper/../Resources/bin/hiddeninput.exe' is not recognized as an internal or external command,
operable program or batch file.

Operation aborted
```

**Comment by mlocati** [comment]
It's working for me on Windows... I'll investigate (just a bit :wink: )

**Comment by Remo** [comment]
I think it's fairly simple. My installation is based on the official 5.7.5.6 download, the file is missing there.. Seems to be a core problem!

**Comment by mlocati** [comment]
In core releases `exe` files are [removed](https://github.com/concrete5/concrete5/blob/5.7.5.6/build/tasks/build-release/clean.js#L52).

Now that we have CLI commands that could be no more the case...

**Comment by mlocati** [comment]
If https://github.com/concrete5/concrete5/pull/3613 will get merged, there'll be no problems (Community Translation will already require the next concrete5 core version)

**Comment by Remo** [comment]
nice, didn't know about that, thanks
